-- MySQL Script generated by MySQL Workbench
-- Mon Oct 21 14:53:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Falta reminder y preference_has_tag

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema meetu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meetu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meetu` DEFAULT CHARACTER SET utf8 ;
USE `meetu` ;

-- -----------------------------------------------------
-- Table `meetu`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`user` ;

CREATE TABLE IF NOT EXISTS `meetu`.`user` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(20) NULL,
  `email` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `image` BLOB NULL,
  `password` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`tag` ;

CREATE TABLE IF NOT EXISTS `meetu`.`tag` (
  `idTags` INT NOT NULL,
  `event_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`event` ;

CREATE TABLE IF NOT EXISTS `meetu`.`event` (
  `idEvent` INT NOT NULL,
  PRIMARY KEY (`idEvent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`plan` ;

CREATE TABLE IF NOT EXISTS `meetu`.`plan` (
  `idEvent` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT(200) NULL,
  PRIMARY KEY (`idEvent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`suggested_budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`suggested_budget` ;

CREATE TABLE IF NOT EXISTS `meetu`.`suggested_budget` (
  `idBudget` INT NOT NULL,
  `amount_o_money` INT NOT NULL,
  `Plan_idEvent` INT NOT NULL,
  PRIMARY KEY (`idBudget`),
  INDEX `fk_Budget_Plan1_idx` (`Plan_idEvent` ASC) ,
  CONSTRAINT `fk_Budget_Plan1`
    FOREIGN KEY (`Plan_idEvent`)
    REFERENCES `meetu`.`plan` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`preference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`preference` ;

CREATE TABLE IF NOT EXISTS `meetu`.`preference` (
  `idPreferences` INT NOT NULL,
  `Users_idUser` INT NOT NULL,
  `event_type_name` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPreferences`, `User_idUser`),
  INDEX `fk_Preferences_User1_idx` (`User_idUser` ASC) ,
  CONSTRAINT `fk_Preferences_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `meetu`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`event_has_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`event_has_tag` ;

CREATE TABLE IF NOT EXISTS `meetu`.`event_has_tag` (
  `Tags_idTags` INT NOT NULL,
  `Event_idEvent` INT NOT NULL,
  PRIMARY KEY (`Tags_idTags`, `Event_idEvent`),
  INDEX `fk_Tags_has_Event_Event1_idx` (`Event_idEvent` ASC) ,
  INDEX `fk_Tags_has_Event_Tags1_idx` (`Tags_idTags` ASC) ,
  CONSTRAINT `fk_Tags_has_Event_Tags1`
    FOREIGN KEY (`Tags_idTags`)
    REFERENCES `meetu`.`tag` (`idTags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_has_Event_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `meetu`.`plan` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`comment` ;

CREATE TABLE IF NOT EXISTS `meetu`.`comment` (
  `commentary` TEXT(200) NOT NULL,
  `date` DATETIME NOT NULL,
  `Plan_idEvent` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  INDEX `fk_Comments_Plan1_idx` (`Plan_idEvent` ASC) ,
  PRIMARY KEY (`User_idUser`),
  CONSTRAINT `fk_Comments_Plan1`
    FOREIGN KEY (`Plan_idEvent`)
    REFERENCES `meetu`.`plan` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `meetu`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`friendship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`friendship` ;

CREATE TABLE IF NOT EXISTS `meetu`.`friendship` (
  `Users_idUser1` INT NOT NULL,
  `Users_idUser2` INT NULL,
  `status` VARCHAR(45) NULL,
  INDEX `fk_Friendship_Users1_idx` (`Users_idUser1` ASC) ,
  INDEX `fk_Friendship_Users2_idx` (`Users_idUser2` ASC) ,
  UNIQUE INDEX `Users_idUser1_UNIQUE` (`Users_idUser1` ASC) ,
  UNIQUE INDEX `Users_idUser2_UNIQUE` (`Users_idUser2` ASC) ,
  CONSTRAINT `fk_Friendship_Users1`
    FOREIGN KEY (`Users_idUser1`)
    REFERENCES `meetu`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friendship_Users2`
    FOREIGN KEY (`Users_idUser2`)
    REFERENCES `meetu`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`preference_has_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`preference_has_tag` ;

CREATE TABLE IF NOT EXISTS `meetu`.`preference_has_tag` (
  `Preferences_idPreferences` INT NOT NULL,
  `Preferences_Users_idUser` INT NOT NULL,
  `Tags_idTags` INT NOT NULL,
  PRIMARY KEY (`Preferences_idPreferences`, `Preferences_Users_idUser`, `Tags_idTags`),
  INDEX `fk_Preferences_has_Tags_Tags1_idx` (`Tags_idTags` ASC) ,
  INDEX `fk_Preferences_has_Tags_Preferences1_idx` (`Preferences_idPreferences` ASC, `Preferences_Users_idUser` ASC) ,
  CONSTRAINT `fk_Preferences_has_Tags_Preferences1`
    FOREIGN KEY (`Preferences_idPreferences` , `Preferences_Users_idUser`)
    REFERENCES `meetu`.`preference` (`idPreferences` , `User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Preferences_has_Tags_Tags1`
    FOREIGN KEY (`Tags_idTags`)
    REFERENCES `meetu`.`tag` (`idTags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `meetu`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`calendar` ;

CREATE TABLE IF NOT EXISTS `meetu`.`calendar` (
  `idCalendar` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `day_number` SMALLINT(2) NOT NULL,
  `day_date` DATETIME NOT NULL,
  `time_in_hours` DATETIME NOT NULL,
  `other_details` TEXT(50) NULL,
  PRIMARY KEY (`idCalendar`),
  INDEX `fk_Calendar_User1_idx` (`User_idUser` ASC) ,
  CONSTRAINT `fk_Calendar_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `meetu`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`reminder` ;

CREATE TABLE IF NOT EXISTS `meetu`.`reminder` (
  `idReminder` INT NOT NULL,
  `schedule_time` DATETIME NOT NULL,
  `Plan_idEvent` INT NOT NULL,
  `Plan_User_idUser` INT NOT NULL,
  PRIMARY KEY (`idReminder`),
  INDEX `fk_Reminder_Plan1_idx` (`Plan_idEvent` ASC) ,
  CONSTRAINT `fk_Reminder_Plan1`
    FOREIGN KEY (`Plan_idEvent`)
    REFERENCES `meetu`.`plan` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `meetu`.`user_has_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`user_has_plan` ;

CREATE TABLE IF NOT EXISTS `meetu`.`user_has_plan` (
  `User_idUser` INT NOT NULL,
  `Plan_idEvent` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Plan_idEvent`),
  INDEX `fk_User_has_Plan_Plan1_idx` (`Plan_idEvent` ASC) ,
  INDEX `fk_User_has_Plan_User1_idx` (`User_idUser` ASC) ,
  CONSTRAINT `fk_User_has_Plan_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `meetu`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Plan_Plan1`
    FOREIGN KEY (`Plan_idEvent`)
    REFERENCES `meetu`.`plan` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`suggested_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`suggested_location` ;

CREATE TABLE IF NOT EXISTS `meetu`.`suggested_location` (
  `idLocation` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `coordinate` POINT NOT NULL,
  `Plan_idEvent` INT NOT NULL,
  PRIMARY KEY (`idLocation`),
  INDEX `fk_Location_Plan1_idx` (`Plan_idEvent` ASC) ,
  CONSTRAINT `fk_Location_Plan1`
    FOREIGN KEY (`Plan_idEvent`)
    REFERENCES `meetu`.`plan` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`suggested_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`suggested_date` ;

CREATE TABLE IF NOT EXISTS `meetu`.`suggested_date` (
  `idSuggested_Dates` INT NOT NULL,
  `start_date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `Plan_idEvent` INT NOT NULL,
  PRIMARY KEY (`idSuggested_Dates`),
  INDEX `fk_Suggested_Dates_Plan1_idx` (`Plan_idEvent` ASC) ,
  CONSTRAINT `fk_Suggested_Dates_Plan1`
    FOREIGN KEY (`Plan_idEvent`)
    REFERENCES `meetu`.`plan` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`rol` ;

CREATE TABLE IF NOT EXISTS `meetu`.`rol` (
  `idroles` INT NOT NULL,
  `role_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`rol_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`rol_has_user` ;

CREATE TABLE IF NOT EXISTS `meetu`.`rol_has_user` (
  `roles_idroles` INT NOT NULL,
  `users_idUser` INT NOT NULL,
  PRIMARY KEY (`roles_idroles`, `users_idUser`),
  INDEX `fk_roles_has_users_users1_idx` (`users_idUser` ASC) ,
  INDEX `fk_roles_has_users_roles1_idx` (`roles_idroles` ASC) ,
  CONSTRAINT `fk_roles_has_users_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `meetu`.`rol` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_users_users1`
    FOREIGN KEY (`users_idUser`)
    REFERENCES `meetu`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meetu`.`rol_has_user_has_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meetu`.`rol_has_user_has_plan` ;

CREATE TABLE IF NOT EXISTS `meetu`.`rol_has_user_has_plan` (
  `roles_has_users_roles_idroles` INT NOT NULL,
  `roles_has_users_users_idUser` INT NOT NULL,
  `plans_idEvent` INT NOT NULL,
  PRIMARY KEY (`roles_has_users_roles_idroles`, `roles_has_users_users_idUser`, `plans_idEvent`),
  INDEX `fk_roles_has_users_has_plans_plans1_idx` (`plans_idEvent` ASC) ,
  INDEX `fk_roles_has_users_has_plans_roles_has_users1_idx` (`roles_has_users_roles_idroles` ASC, `roles_has_users_users_idUser` ASC) ,
  CONSTRAINT `fk_roles_has_users_has_plans_roles_has_users1`
    FOREIGN KEY (`roles_has_users_roles_idroles` , `roles_has_users_users_idUser`)
    REFERENCES `meetu`.`rol_has_user` (`roles_idroles` , `users_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_users_has_plans_plans1`
    FOREIGN KEY (`plans_idEvent`)
    REFERENCES `meetu`.`plan` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
